In [120]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from scipy import stats

In [121]:
data=pd.read_csv(r'D:\Cars24_Analysis\bewakoof_products_from_url_file_selenium.csv')
data.head()

,Category URL,Title,Selling Price,MRP,Discount,Rating
0,https://www.bewakoof.com/top-wear-for-men,Men's White T-shirt,₹399,₹999,60% OFF,4.6
1,https://www.bewakoof.com/top-wear-for-men,Men's Black Oversized T-shirt,₹699,"₹1,349",48% OFF,4.6
2,https://www.bewakoof.com/top-wear-for-men,Men's Baby Lavender Catch Groove Graphic Print...,₹599,"₹1,899",68% OFF,4.6
3,https://www.bewakoof.com/top-wear-for-men,Men's Beige Blast Music Typography Oversized T...,₹599,"₹1,899",68% OFF,4.6
4,https://www.bewakoof.com/top-wear-for-men,Men's Black Freedom Sounds Graphic Printed Ove...,₹799,"₹2,199",63% OFF,4.6

In [122]:
data1=pd.read_csv(r'D:\Cars24_Analysis\bewakoof_products_from_url_file_selenium67.csv')
data1.head()

,Category URL,Title,Selling Price,MRP,Discount,Rating
0,https://www.bewakoof.com/top-wear-for-women,Women's Orange Boyfriend T-shirt,₹399,₹699,42% OFF,4.3
1,https://www.bewakoof.com/top-wear-for-women,Women's White Boyfriend T-shirt,₹399,₹999,60% OFF,4.3
2,https://www.bewakoof.com/top-wear-for-women,Women's Ginger Root Brown Pocket Shine Graphic...,₹449,"₹1,399",67% OFF,4.3
3,https://www.bewakoof.com/top-wear-for-women,Women's Pink & White Camo Printed Oversized T-...,₹599,"₹1,149",47% OFF,4.3
4,https://www.bewakoof.com/top-wear-for-women,Women's Black & White All Over Printed Oversiz...,₹599,₹999,40% OFF,4.3

In [123]:
df=pd.concat([data,data1],ignore_index=True)
df.head()

,Category URL,Title,Selling Price,MRP,Discount,Rating
0,https://www.bewakoof.com/top-wear-for-men,Men's White T-shirt,₹399,₹999,60% OFF,4.6
1,https://www.bewakoof.com/top-wear-for-men,Men's Black Oversized T-shirt,₹699,"₹1,349",48% OFF,4.6
2,https://www.bewakoof.com/top-wear-for-men,Men's Baby Lavender Catch Groove Graphic Print...,₹599,"₹1,899",68% OFF,4.6
3,https://www.bewakoof.com/top-wear-for-men,Men's Beige Blast Music Typography Oversized T...,₹599,"₹1,899",68% OFF,4.6
4,https://www.bewakoof.com/top-wear-for-men,Men's Black Freedom Sounds Graphic Printed Ove...,₹799,"₹2,199",63% OFF,4.6

In [124]:
df.shape

(952, 6)

# Data_understanding

In [125]:
print("the shape of the dataframe is:", df.shape)

the shape of the dataframe is: (952, 6)

In [126]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 952 entries, 0 to 951
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Category URL   952 non-null    object
 1   Title          952 non-null    object
 2   Selling Price  952 non-null    object
 3   MRP            949 non-null    object
 4   Discount       949 non-null    object
 5   Rating         952 non-null    float64
dtypes: float64(1), object(5)
memory usage: 44.8+ KB
None

In [127]:
df.describe()

           Rating
count  952.000000
mean     4.445693
std      0.106084
min      4.300000
25%      4.400000
50%      4.400000
75%      4.500000
max      4.700000

# Check missing values

In [128]:
df.isnull().sum()

Category URL     0
Title            0
Selling Price    0
MRP              3
Discount         3
Rating           0
dtype: int64

In [129]:
df[df.duplicated()]

Empty DataFrame
Columns: [Category URL, Title, Selling Price, MRP, Discount, Rating]
Index: []

In [130]:
df.shape

(952, 6)

In [131]:
df.columns

Index(['Category URL', 'Title', 'Selling Price', 'MRP', 'Discount', 'Rating'], dtype='object')

In [132]:
df.drop(['Category URL'], axis=1, inplace=True)

In [133]:
df.head()

,Title,Selling Price,MRP,Discount,Rating
0,Men's White T-shirt,₹399,₹999,60% OFF,4.6
1,Men's Black Oversized T-shirt,₹699,"₹1,349",48% OFF,4.6
2,Men's Baby Lavender Catch Groove Graphic Print...,₹599,"₹1,899",68% OFF,4.6
3,Men's Beige Blast Music Typography Oversized T...,₹599,"₹1,899",68% OFF,4.6
4,Men's Black Freedom Sounds Graphic Printed Ove...,₹799,"₹2,199",63% OFF,4.6

# 1) CLEAN NUMERIC COLUMNS

In [ ]:


df["Selling Price"] = (
    df["Selling Price"].astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)
df["Selling Price"] = pd.to_numeric(df["Selling Price"], errors="coerce")

df["MRP"] = (
    df["MRP"].astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)
df["MRP"] = pd.to_numeric(df["MRP"], errors="coerce")

df["Discount"] = (
    df["Discount"].astype(str)
    .str.replace("% OFF", "", regex=False)
    .str.replace("%", "", regex=False)
    .str.strip()
)
df["Discount"] = pd.to_numeric(df["Discount"], errors="coerce")

df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce")

# Derived business columns
df["Discount_Amount"] = df["MRP"] - df["Selling Price"]
df["Discount_Computed_%"] = round(
    (df["Discount_Amount"] / df["MRP"]) * 100, 1
)

NameError: name 'df' is not defined

In [ ]:


def extract_features(title):
    title = str(title)
    title_lower = title.lower()

    # Gender (FIXED)

    if "women" in title_lower or "women's" in title_lower or "womens" in title_lower:
        gender = "Women"
    elif "men" in title_lower or "men's" in title_lower or "mens" in title_lower:
        gender = "Men"
    else:
        gender = "Unisex"

    # Color
    colors = [
        "black","white","blue","green","beige","brown","grey","gray","pink",
        "red","navy","olive","purple","maroon","orange","yellow","teal",
        "lavender","charcoal","cream","off white"
    ]
    color = next((c.title() for c in colors if c in title_lower), None)

    # Fit
  
    fits = ["oversized", "slim fit", "regular", "baggy", "super loose", "boyfriend"]
    fit = next((f.title() for f in fits if f in title_lower), None)

    # Product Type
   
    product_types = [
        "t-shirt","hoodie","sweatshirt","shirt","jacket","jeans","joggers",
        "pants","shorts","vest","pyjamas","boxers","sweater","co-ordinates",
        "track pants","windcheater"
    ]
    product_type = next((p.title() for p in product_types if p in title_lower), None)

    # Print Type
    
    if "graphic" in title_lower:
        print_type = "Graphic"
    elif "typography" in title_lower:
        print_type = "Typography"
    elif "printed" in title_lower:
        print_type = "Printed"
    else:
        print_type = "Solid"

    
    # Wash Type

    if "acid wash" in title_lower:
        wash_type = "Acid Wash"
    elif "tie & dye" in title_lower or "tie and dye" in title_lower:
        wash_type = "Tie & Dye"
    else:
        wash_type = None

  
    # Theme / Collab
   
    themes = ["marvel","batman","garfield","anime","naruto","one piece","mickey"]
    theme = next((t.title() for t in themes if t in title_lower), None)

    return pd.Series([
        gender, color, fit, product_type, print_type, wash_type, theme
    ])


# APPLY FEATURE EXTRACTION

df[[
    "Gender", "Color", "Fit", "Product_Type",
    "Print_Type", "Wash_Type", "Theme"
]] = df["Title"].apply(extract_features)



# CATEGORY MAPPING

category_map = {
    "T-Shirt": "Topwear",
    "Hoodie": "Outerwear",
    "Sweatshirt": "Outerwear",
    "Shirt": "Topwear",
    "Jacket": "Outerwear",
    "Jeans": "Bottomwear",
    "Joggers": "Bottomwear",
    "Pants": "Bottomwear",
    "Shorts": "Bottomwear",
    "Vest": "Topwear",
    "Pyjamas": "Loungewear",
    "Boxers": "Loungewear",
    "Sweater": "Outerwear",
    "Co-Ordinates": "Set",
    "Track Pants": "Bottomwear",
    "Windcheater": "Outerwear"
}

df["Category"] = df["Product_Type"].map(category_map)

In [ ]:
df.head()

,Title,Selling Price,MRP,Discount,Rating,Discount_Amount,Discount_Computed_%,Gender,Color,Fit,Product_Type,Print_Type,Wash_Type,Theme,Category
0,Men's White T-shirt,399,999.0,60.0,4.6,600.0,60.1,Men,White,None,T-Shirt,Solid,None,None,Topwear
1,Men's Black Oversized T-shirt,699,1349.0,48.0,4.6,650.0,48.2,Men,Black,Oversized,T-Shirt,Solid,None,None,Topwear
2,Men's Baby Lavender Catch Groove Graphic Print...,599,1899.0,68.0,4.6,1300.0,68.5,Men,Lavender,Oversized,T-Shirt,Graphic,None,None,Topwear
3,Men's Beige Blast Music Typography Oversized T...,599,1899.0,68.0,4.6,1300.0,68.5,Men,Beige,Oversized,T-Shirt,Typography,None,None,Topwear
4,Men's Black Freedom Sounds Graphic Printed Ove...,799,2199.0,63.0,4.6,1400.0,63.7,Men,Black,Oversized,T-Shirt,Graphic,Acid Wash,None,Topwear

In [ ]:
df["Gender"].unique()

array(['Men', 'Women'], dtype=object)

In [ ]:
df.columns

Index(['Title', 'Selling Price', 'MRP', 'Discount', 'Rating',
       'Discount_Amount', 'Discount_Computed_%', 'Gender', 'Color', 'Fit',
       'Product_Type', 'Print_Type', 'Wash_Type', 'Theme', 'Category'],
      dtype='object')

In [ ]:
df.isnull().sum()/len(df)*100

Title                   0.000000
Selling Price           0.000000
MRP                     0.315126
Discount                0.315126
Rating                  0.000000
Discount_Amount         0.315126
Discount_Computed_%     0.315126
Gender                  0.000000
Color                   2.941176
Fit                    38.970588
Product_Type            0.945378
Print_Type              0.000000
Wash_Type              97.163866
Theme                  97.268908
Category                0.945378
dtype: float64

In [ ]:
df['Color'].fillna('Unknown',inplace=True)
df['Fit'].fillna('Unknown',inplace=True)
df.drop(columns=["Title","Wash_Type","Theme"],inplace=True)
df.dropna(inplace=True)
df.isnull().sum()/len(df)

C:\Users\User\AppData\Local\Temp\ipykernel_20700\910310658.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Color'].fillna('Unknown',inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_20700\910310658.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fit'].fillna('Unknown',inplace=True)

Selling Price          0.0
MRP                    0.0
Discount               0.0
Rating                 0.0
Discount_Amount        0.0
Discount_Computed_%    0.0
Gender                 0.0
Color                  0.0
Fit                    0.0
Product_Type           0.0
Print_Type             0.0
Category               0.0
dtype: float64

In [ ]:
df.shape

(940, 12)

In [ ]:
df.head()

,Selling Price,MRP,Discount,Rating,Discount_Amount,Discount_Computed_%,Gender,Color,Fit,Product_Type,Print_Type,Category
0,399,999.0,60.0,4.6,600.0,60.1,Men,White,Unknown,T-Shirt,Solid,Topwear
1,699,1349.0,48.0,4.6,650.0,48.2,Men,Black,Oversized,T-Shirt,Solid,Topwear
2,599,1899.0,68.0,4.6,1300.0,68.5,Men,Lavender,Oversized,T-Shirt,Graphic,Topwear
3,599,1899.0,68.0,4.6,1300.0,68.5,Men,Beige,Oversized,T-Shirt,Typography,Topwear
4,799,2199.0,63.0,4.6,1400.0,63.7,Men,Black,Oversized,T-Shirt,Graphic,Topwear

In [ ]:
df["Gender"].unique()

array(['Men', 'Women'], dtype=object)

In [ ]:
df.to_csv(r"D:\Cars24_Analysis\Notebooks\bewakoof_cleaned.csv")

# Data Cleaning report

Berfore cleaning

In [ ]:
#   Column         Non-Null Count  Dtype  
# ---  ------         --------------  -----  
#  0   Category URL   952 non-null    object 
#  1   Title          952 non-null    object 
#  2   Selling Price  952 non-null    object 
#  3   MRP            949 non-null    object 
#  4   Discount       949 non-null    object 
#  5   Rating         952 non-null    float64

# the shape of the dataframe is: (952, 6)

After cleaning

extracted below feature from the Title(column) and performed Data cleaning

In [8]:
#        'Discount_Amount', 'Discount_Computed_%', 'Gender', 'Color', 'Fit',
#        'Product_Type', 'Print_Type', 'Wash_Type', 'Theme', 'Category'

In [9]:
# Selling Price & MRP cleaning: Converted text prices to numeric to analyze true price distribution.

# Discount cleaning: Standardized discount percentages for fair comparison across products.

# Rating conversion: Enabled numerical analysis of customer satisfaction.

# Discount Amount: Captures actual rupee savings per product.

# Computed Discount %: Validates listed discounts against real pricing.

# Gender extraction: Helps study gender-wise pricing and discount patterns.

# Color extraction: Enables color-based preference and pricing analysis.

# Fit extraction: Analyzes style trends and fit-wise price differences.

# Product type extraction: Allows comparison across apparel types.

# Print type: Distinguishes solid vs printed pricing behavior.

# Wash type: Identifies premium treatments affecting price.

# Theme detection: Highlights collaboration/licensed products with premium pricing.

# Category mapping: Simplifies high-level category performance analysis.

# missing values treatment

In [10]:
# Filled missing Color & Fit: Assigned 'Unknown' to retain products with incomplete style information.

# Dropped Title, Wash_Type, Theme: Removed non-essential or sparse features to reduce noise.

# Dropped remaining missing values: Ensured a clean, complete dataset for reliable analysis.

# Null percentage check: Verified that the final dataset contains no missing values and is analysis-ready.

# final data

In [11]:
 #   Column               Non-Null Count  Dtype  
# ---  ------               --------------  -----  
#  0   Unnamed: 0           940 non-null    int64  
#  1   Selling Price        940 non-null    int64  
#  2   MRP                  940 non-null    float64
#  3   Discount             940 non-null    float64
#  4   Rating               940 non-null    float64
#  5   Discount_Amount      940 non-null    float64
#  6   Discount_Computed_%  940 non-null    float64
#  7   Gender               940 non-null    object 
#  8   Color                940 non-null    object 
#  9   Fit                  940 non-null    object 
#  10  Product_Type         940 non-null    object 
#  11  Print_Type           940 non-null    object 
#  12  Category             940 non-null    object 

# shape of the dataframe : (940, 13)