In [8]:
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import re
import requests

In [9]:
options=Options()
options.add_argument('--start-maximized')

service=Service(ChromeDriverManager().install())

driver=webdriver.Chrome(service=service,options=options)

In [10]:
# url="https://www.bewakoof.com/men-clothing"
url='https://www.bewakoof.com/men-clothing?category=shirt&'
driver.get(url)

In [11]:

import time

all_products = []

while True:
    time.sleep(2)

    # Collect data from current page
    for tag in driver.find_elements(By.XPATH, "//span[@data-testid='product-title']"):
        all_products.append(tag.text)

    print("Total collected:", len(all_products))

    try:
        # Click Next page
        next_btn = WebDriverWait(driver, 5).until(
            EC.element_to_be_clickable((By.XPATH, "//a[contains(@aria-label,'Next') or contains(text(),'Next')]"))
        )
        driver.execute_script("arguments[0].click();", next_btn)

    except:
        print("No more pages")
        break

Total collected: 20
No more pages

In [12]:
product_names = []

for tag in driver.find_elements(By.XPATH, "//span[@data-testid='product-title']"):
    text = tag.text
    a = re.findall(r'(.+)', text)      # full text
    product_names.extend(a)

print(len(product_names))

20

In [13]:
product_names

["Men's Rust Orange & Blue Checked Oversized Shirt",
 "Men's Brown Embroidered Oversized Shirt",
 "Men's Petrol Blue Oversized Shirt",
 "Men's Blue & White Checked Oversized Shirt",
 "Men's Yellow & White Checked Oversized Shirt",
 "Men's Pink Cotton Linen Shirt",
 "Men's Maroon & White Checked Shirts",
 "Men's Green Graphic Printed Oversized Shirt",
 "Men's Brown & White Checked Oversized Shirt",
 "Men's Beige Checked Cotton Linen Shirt",
 "Men's Indigo Blue Evolve Typography Washed Denim Shirt",
 "Men's Toffee Brown Cotton Linen Shirt",
 "Men's Maroon & White Checked Oversized Hooded Shirt",
 "Men's Beige & Blue Checked Cotton Linen Shirt",
 "Men's Brown Washed Shirt",
 "Men's Rust Brown All Over Printed Oversized Shirt",
 "Men's White & Rust Orange Checked Oversized Shirt",
 "Men's Brown & Beige Checked Oversized Shirt",
 "Men's White All Over Printed Oversized Shirt",
 "Men's Bold Red & Navy Blue Checked Shirt"]

In [14]:
selling_price = []

for tag in driver.find_elements(By.XPATH, "//span[@data-testid='product-card-selling-price']"):
    text = tag.text
    a = re.findall(r'₹(.+)', text)     # extract only number
    selling_price.extend(a)

print(selling_price)

['1,699', '1,199', '999', '1,499', '1,499', '1,499', '1,299', '1,299', '1,299', '1,499', '1,699', '1,499', '1,899', '1,499', '1,699', '999', '1,499', '1,499', '999', '1,299']

In [15]:
print(len(selling_price))

20

In [16]:
mrp = []

for tag in driver.find_elements(By.XPATH, "//span[@data-testid='product-card-mrp']"):
    text = tag.text
    a = re.findall(r'₹(.+)', text)
    mrp.extend(a)

print(mrp)

['3,499', '2,699', '2,399', '3,399', '3,399', '2,999', '2,999', '1,499', '3,599', '3,499', '1,899', '2,999', '4,099', '3,499', '3,499', '2,599', '3,599', '3,399', '2,599', '3,799']

In [17]:
discount = []

for tag in driver.find_elements(By.XPATH, "//span[@data-testid='product-card-discount']"):
    text = tag.text
    a = re.findall(r'(\d+)%', text)   # only percentage
    discount.extend(a)

print(discount)

['51', '55', '58', '55', '55', '50', '56', '13', '63', '57', '10', '50', '53', '57', '51', '61', '58', '55', '61', '65']

In [18]:
ratings = []

for tag in driver.find_elements(By.XPATH, "//span"):
    text = tag.text
    a = re.findall(r'^[1-5]\.\d$', text)   # only valid star ratings
    ratings.extend(a)

print(ratings)

['4.4', '4.6', '4.6', '4.4', '4.5', '4.4', '4.5', '4.6', '4.6', '4.6', '4.6', '4.4', '4.6', '4.6', '4.6', '4.6', '4.6', '4.5', '4.6', '4.5']

In [19]:
import re
from selenium.webdriver.common.by import By

offers = []

for tag in driver.find_elements(By.XPATH, "//span[contains(text(),'BUY')]"):
    text = tag.text
    a = re.findall(r'BUY\s*\d+\s*FOR\s*\d+', text)
    offers.extend(a)

print(offers)

[]

In [20]:


product_names = []

for tag in driver.find_elements(By.XPATH, "//span[@data-testid='product-title']"):
    text = tag.text
    a = re.findall(r'(.+)', text)      # full text
    product_names.extend(a)

print(len(product_names))



selling_price = []

for tag in driver.find_elements(By.XPATH, "//span[@data-testid='product-card-selling-price']"):
    text = tag.text
    a = re.findall(r'₹(.+)', text)     # extract only number
    selling_price.extend(a)

print(selling_price)




mrp = []

for tag in driver.find_elements(By.XPATH, "//span[@data-testid='product-card-mrp']"):
    text = tag.text
    a = re.findall(r'₹(.+)', text)
    mrp.extend(a)

print(mrp)





discount = []

for tag in driver.find_elements(By.XPATH, "//span[@data-testid='product-card-discount']"):
    text = tag.text
    a = re.findall(r'(\d+)%', text)   # only percentage
    discount.extend(a)

print(discount)



ratings = []

for tag in driver.find_elements(By.XPATH, "//span"):
    text = tag.text
    a = re.findall(r'^[1-5]\.\d$', text)   
    ratings.extend(a)

print(ratings)
offers = []

for tag in driver.find_elements(By.XPATH, "//span[contains(text(),'BUY')]"):
    text = tag.text
    a = re.findall(r'BUY\s*\d+\s*FOR\s*\d+', text)
    offers.extend(a)

print(offers)

20
['1,699', '1,199', '999', '1,499', '1,499', '1,499', '1,299', '1,299', '1,299', '1,499', '1,699', '1,499', '1,899', '1,499', '1,699', '999', '1,499', '1,499', '999', '1,299']
['3,499', '2,699', '2,399', '3,399', '3,399', '2,999', '2,999', '1,499', '3,599', '3,499', '1,899', '2,999', '4,099', '3,499', '3,499', '2,599', '3,599', '3,399', '2,599', '3,799']
['51', '55', '58', '55', '55', '50', '56', '13', '63', '57', '10', '50', '53', '57', '51', '61', '58', '55', '61', '65']

KeyboardInterrupt:

In [ ]:
import re
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()

base_url = "https://www.bewakoof.com/men-clothing?page="

product_names = []
selling_price = []
mrp = []
discount = []
ratings = []
offers = []

# Bewakoof has ~150 pages (20 products per page)
for page in range(1, 160):   # 1 → 159
    print("Scraping page:", page)

    driver.get(base_url + str(page))
    time.sleep(4)

    # Wait until products load
    if not driver.find_elements(By.XPATH, "//span[@data-testid='product-title']"):
        print("No more products")
        break

    # ---- YOUR ORIGINAL CODE (unchanged) ----

    for tag in driver.find_elements(By.XPATH, "//span[@data-testid='product-title']"):
        text = tag.text
        a = re.findall(r'(.+)', text)
        product_names.extend(a)

    for tag in driver.find_elements(By.XPATH, "//span[@data-testid='product-card-selling-price']"):
        text = tag.text
        a = re.findall(r'₹(.+)', text)
        selling_price.extend(a)

    for tag in driver.find_elements(By.XPATH, "//span[@data-testid='product-card-mrp']"):
        text = tag.text
        a = re.findall(r'₹(.+)', text)
        mrp.extend(a)

    for tag in driver.find_elements(By.XPATH, "//span[@data-testid='product-card-discount']"):
        text = tag.text
        a = re.findall(r'(\d+)%', text)
        discount.extend(a)

    for tag in driver.find_elements(By.XPATH, "//span"):
        text = tag.text
        a = re.findall(r'^[1-5]\.\d$', text)
        ratings.extend(a)

    for tag in driver.find_elements(By.XPATH, "//span[contains(text(),'BUY')]"):
        text = tag.text
        a = re.findall(r'BUY\s*\d+\s*FOR\s*\d+', text)
        offers.extend(a)

    print("Total so far:", len(product_names))

driver.quit()

# SAVE
df = pd.DataFrame({
    "Product": product_names,
    "Price": selling_price,
    "MRP": mrp,
    "Discount": discount,
    "Rating": ratings[:len(product_names)],
    "Offer": offers
})

df.to_csv("bewakoof_3000_products.csv", index=False)
print("Saved bewakoof_3000_products.csv")

Scraping page: 1
Total so far: 20
Scraping page: 2
Total so far: 40
Scraping page: 3
Total so far: 60
Scraping page: 4
Total so far: 80
Scraping page: 5
Total so far: 100
Scraping page: 6
Total so far: 120
Scraping page: 7
Total so far: 140
Scraping page: 8
Total so far: 160
Scraping page: 9
Total so far: 180
Scraping page: 10
Total so far: 200
Scraping page: 11
Total so far: 220
Scraping page: 12
Total so far: 240
Scraping page: 13
Total so far: 260
Scraping page: 14
Total so far: 280
Scraping page: 15
Total so far: 300
Scraping page: 16
Total so far: 320
Scraping page: 17
Total so far: 340
Scraping page: 18
Total so far: 360
Scraping page: 19
Total so far: 380
Scraping page: 20
Total so far: 400
Scraping page: 21
Total so far: 420
Scraping page: 22
Total so far: 440
Scraping page: 23
Total so far: 460
Scraping page: 24
Total so far: 480
Scraping page: 25
Total so far: 500
Scraping page: 26
Total so far: 520
Scraping page: 27
Total so far: 540
Scraping page: 28
Total so far: 560
Scraping page: 29
Total so far: 580
Scraping page: 30
Total so far: 600
Scraping page: 31
Total so far: 620
Scraping page: 32
Total so far: 640
Scraping page: 33
Total so far: 660
Scraping page: 34
Total so far: 680
Scraping page: 35
Total so far: 700
Scraping page: 36
Total so far: 720
Scraping page: 37
Total so far: 740
Scraping page: 38
Total so far: 760
Scraping page: 39
Total so far: 780
Scraping page: 40
Total so far: 800
Scraping page: 41
Total so far: 820
Scraping page: 42
Total so far: 840
Scraping page: 43
Total so far: 860
Scraping page: 44
Total so far: 880
Scraping page: 45
Total so far: 900
Scraping page: 46
Total so far: 920
Scraping page: 47
Total so far: 940
Scraping page: 48
Total so far: 960
Scraping page: 49
Total so far: 980
Scraping page: 50
Total so far: 1000
Scraping page: 51
Total so far: 1020
Scraping page: 52
Total so far: 1040
Scraping page: 53
Total so far: 1060
Scraping page: 54
Total so far: 1080
Scraping page: 55
Total so far: 1100
Scraping page: 56
Total so far: 1120
Scraping page: 57
Total so far: 1140
Scraping page: 58
Total so far: 1160
Scraping page: 59
Total so far: 1180
Scraping page: 60
Total so far: 1200
Scraping page: 61
Total so far: 1220
Scraping page: 62
Total so far: 1240
Scraping page: 63
Total so far: 1260
Scraping page: 64
Total so far: 1280
Scraping page: 65
Total so far: 1300
Scraping page: 66
Total so far: 1320
Scraping page: 67
Total so far: 1340
Scraping page: 68
Total so far: 1360
Scraping page: 69
Total so far: 1380
Scraping page: 70
Total so far: 1400
Scraping page: 71
Total so far: 1420
Scraping page: 72
Total so far: 1440
Scraping page: 73
Total so far: 1460
Scraping page: 74
Total so far: 1480
Scraping page: 75
Total so far: 1500
Scraping page: 76
Total so far: 1520
Scraping page: 77
Total so far: 1540
Scraping page: 78
Total so far: 1560
Scraping page: 79
Total so far: 1580
Scraping page: 80
Total so far: 1600
Scraping page: 81
Total so far: 1620
Scraping page: 82
Total so far: 1640
Scraping page: 83
Total so far: 1660
Scraping page: 84
Total so far: 1680
Scraping page: 85
Total so far: 1700
Scraping page: 86
Total so far: 1720
Scraping page: 87
Total so far: 1740
Scraping page: 88
Total so far: 1760
Scraping page: 89
Total so far: 1780
Scraping page: 90
Total so far: 1800
Scraping page: 91
Total so far: 1820
Scraping page: 92
Total so far: 1840
Scraping page: 93
Total so far: 1860
Scraping page: 94
Total so far: 1880
Scraping page: 95
Total so far: 1900
Scraping page: 96
Total so far: 1920
Scraping page: 97
Total so far: 1940
Scraping page: 98
Total so far: 1960
Scraping page: 99
Total so far: 1980
Scraping page: 100
Total so far: 2000
Scraping page: 101
Total so far: 2020
Scraping page: 102
Total so far: 2040
Scraping page: 103
Total so far: 2060
Scraping page: 104
Total so far: 2080
Scraping page: 105
Total so far: 2100
Scraping page: 106
Total so far: 2120
Scraping page: 107
Total so far: 2140
Scraping page: 108
Total so far: 2160
Scraping page: 109
Total so far: 2180
Scraping page: 110
Total so far: 2200
Scraping page: 111
Total so far: 2220
Scraping page: 112
Total so far: 2240
Scraping page: 113
Total so far: 2260
Scraping page: 114
Total so far: 2280
Scraping page: 115
Total so far: 2300
Scraping page: 116
Total so far: 2320
Scraping page: 117
Total so far: 2340
Scraping page: 118
Total so far: 2360
Scraping page: 119
Total so far: 2380
Scraping page: 120
Total so far: 2400
Scraping page: 121
Total so far: 2420
Scraping page: 122
Total so far: 2440
Scraping page: 123
Total so far: 2460
Scraping page: 124
Total so far: 2480
Scraping page: 125
Total so far: 2500
Scraping page: 126
Total so far: 2520
Scraping page: 127
Total so far: 2540
Scraping page: 128
Total so far: 2560
Scraping page: 129
Total so far: 2580
Scraping page: 130
Total so far: 2600
Scraping page: 131
Total so far: 2620
Scraping page: 132
Total so far: 2640
Scraping page: 133
Total so far: 2660
Scraping page: 134
Total so far: 2680
Scraping page: 135
Total so far: 2700
Scraping page: 136
Total so far: 2720
Scraping page: 137
Total so far: 2740
Scraping page: 138
Total so far: 2760
Scraping page: 139
Total so far: 2780
Scraping page: 140
Total so far: 2800
Scraping page: 141
Total so far: 2820
Scraping page: 142
Total so far: 2840
Scraping page: 143
Total so far: 2860
Scraping page: 144
Total so far: 2880
Scraping page: 145
Total so far: 2900
Scraping page: 146
Total so far: 2920
Scraping page: 147
Total so far: 2940
Scraping page: 148
Total so far: 2960
Scraping page: 149
Total so far: 2980
Scraping page: 150
Total so far: 3000
Scraping page: 151
Total so far: 3020
Scraping page: 152
Total so far: 3040
Scraping page: 153
Total so far: 3060
Scraping page: 154
Total so far: 3080
Scraping page: 155
Total so far: 3100
Scraping page: 156
Total so far: 3120
Scraping page: 157
Total so far: 3140
Scraping page: 158
Total so far: 3160
Scraping page: 159
Total so far: 3180

ValueError: All arrays must be of the same length

In [ ]:
len(product_names)

3180

In [ ]:
 len(offers)

2385

In [ ]:
# SAVE
df = pd.DataFrame({
    "Product": product_names,
    "Price": selling_price,
    "MRP": mrp,
    "Discount": discount,
    "Rating": ratings[:len(product_names)],
    "Offer": offers
})

df.to_csv("bewakoof_3000_products.csv", index=False)
print("Saved bewakoof_3000_products.csv")

In [ ]:
print(len(product_names))
print(len(mrp))
print(len(selling_price))
print(len(discount))
print(len(ratings))
print(len(offers))

3180
3180
3180
3180
2862
2385

In [ ]:
product_names1 = []
selling_price1 = []
mrp1 = []
discount1 = []
ratings1 = []
offers1 = []

In [ ]:
import re
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

# SPEED UP CHROME
chrome_options = Options()
chrome_options.add_argument("--headless=new")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--blink-settings=imagesEnabled=false")

prefs = {
    "profile.managed_default_content_settings.images": 2,
    "profile.default_content_setting_values.notifications": 2
}
chrome_options.add_experimental_option("prefs", prefs)

driver = webdriver.Chrome(options=chrome_options)

base_url = "https://www.bewakoof.com/men-clothing?page="
rows = []

for page in range(1, 200):
    print("Scraping page:", page)

    driver.get(base_url + str(page))

    # Wait ONLY until product titles load
    t0 = time.time()
    while time.time() - t0 < 6:
        if driver.find_elements(By.XPATH, "//span[@data-testid='product-title']"):
            break
        time.sleep(0.2)

    products = driver.find_elements(By.XPATH, "//span[@data-testid='product-title']/ancestor::div[2]")

    if not products:
        print("No more products")
        break

    for product in products:
        try:
            title = product.find_element(By.XPATH, ".//span[@data-testid='product-title']").text
        except:
            title = ""

        try:
            sp = re.findall(r'₹(\d+)', product.find_element(By.XPATH, ".//span[@data-testid='product-card-selling-price']").text)[0]
        except:
            sp = ""

        try:
            mrp1 = re.findall(r'₹(\d+)', product.find_element(By.XPATH, ".//span[@data-testid='product-card-mrp']").text)[0]
        except:
            mrp1 = ""

        try:
            disc = re.findall(r'(\d+)%', product.find_element(By.XPATH, ".//span[@data-testid='product-card-discount']").text)[0]
        except:
            disc = ""

        try:
            rating1 = re.findall(r'[1-5]\.\d', product.text)[0]
        except:
            rating1 = ""

        try:
            offer1 = re.findall(r'BUY\s*\d+\s*FOR\s*\d+', product.text)[0]
        except:
            offer1 = ""

        rows.append([title, sp, mrp1, disc, rating1, offer1])
    print("Total collected:", len(rows))

driver.quit()

df = pd.DataFrame(rows, columns=["Title","Selling Price","MRP","Discount %","Rating","Offer"])
df.to_csv("bewakoof_3000_products.csv", index=False)
print("Saved bewakoof_3000_products.csv")

Scraping page: 1
Total collected: 20
Scraping page: 2
Total collected: 40
Scraping page: 3
Total collected: 60
Scraping page: 4
Total collected: 80
Scraping page: 5
Total collected: 100
Scraping page: 6
Total collected: 120
Scraping page: 7
Total collected: 140
Scraping page: 8
Total collected: 160
Scraping page: 9
Total collected: 180
Scraping page: 10
Total collected: 200
Scraping page: 11
Total collected: 220
Scraping page: 12
Total collected: 240
Scraping page: 13
Total collected: 260
Scraping page: 14
Total collected: 280
Scraping page: 15
Total collected: 300
Scraping page: 16
Total collected: 320
Scraping page: 17
Total collected: 340
Scraping page: 18
Total collected: 360
Scraping page: 19
Total collected: 380
Scraping page: 20
Total collected: 400
Scraping page: 21
Total collected: 420
Scraping page: 22
Total collected: 440
Scraping page: 23
Total collected: 460
Scraping page: 24
Total collected: 480
Scraping page: 25
Total collected: 500
Scraping page: 26
Total collected: 520
Scraping page: 27
Total collected: 540
Scraping page: 28
Total collected: 560
Scraping page: 29
Total collected: 580
Scraping page: 30
Total collected: 600
Scraping page: 31
Total collected: 620
Scraping page: 32
Total collected: 640
Scraping page: 33
Total collected: 660
Scraping page: 34
Total collected: 680
Scraping page: 35
Total collected: 700
Scraping page: 36
Total collected: 720
Scraping page: 37
Total collected: 740
Scraping page: 38
Total collected: 760
Scraping page: 39
Total collected: 780
Scraping page: 40
Total collected: 800
Scraping page: 41
Total collected: 820
Scraping page: 42
Total collected: 840
Scraping page: 43
Total collected: 860
Scraping page: 44
Total collected: 880
Scraping page: 45
Total collected: 900
Scraping page: 46
Total collected: 920
Scraping page: 47
Total collected: 940
Scraping page: 48
Total collected: 960
Scraping page: 49
Total collected: 980
Scraping page: 50
Total collected: 1000
Scraping page: 51
Total collected: 1020
Scraping page: 52
Total collected: 1040
Scraping page: 53
Total collected: 1060
Scraping page: 54
Total collected: 1080
Scraping page: 55
Total collected: 1100
Scraping page: 56
Total collected: 1120
Scraping page: 57
Total collected: 1140
Scraping page: 58
Total collected: 1160
Scraping page: 59
Total collected: 1180
Scraping page: 60
Total collected: 1200
Scraping page: 61
Total collected: 1220
Scraping page: 62
Total collected: 1240
Scraping page: 63
Total collected: 1260
Scraping page: 64
Total collected: 1280
Scraping page: 65
Total collected: 1300
Scraping page: 66
Total collected: 1320
Scraping page: 67
Total collected: 1340
Scraping page: 68
Total collected: 1360
Scraping page: 69
Total collected: 1380
Scraping page: 70
Total collected: 1400
Scraping page: 71
Total collected: 1420
Scraping page: 72
Total collected: 1440
Scraping page: 73
Total collected: 1460
Scraping page: 74
Total collected: 1480
Scraping page: 75
Total collected: 1500
Scraping page: 76
Total collected: 1520
Scraping page: 77
Total collected: 1540
Scraping page: 78
Total collected: 1560
Scraping page: 79
Total collected: 1580
Scraping page: 80
Total collected: 1600
Scraping page: 81
Total collected: 1620
Scraping page: 82
Total collected: 1640
Scraping page: 83
Total collected: 1660
Scraping page: 84
Total collected: 1680
Scraping page: 85
Total collected: 1700
Scraping page: 86
Total collected: 1720
Scraping page: 87
Total collected: 1740
Scraping page: 88
Total collected: 1760
Scraping page: 89
Total collected: 1780
Scraping page: 90
Total collected: 1800
Scraping page: 91
Total collected: 1820
Scraping page: 92
Total collected: 1840
Scraping page: 93
Total collected: 1860
Scraping page: 94
Total collected: 1880
Scraping page: 95
Total collected: 1900
Scraping page: 96
Total collected: 1920
Scraping page: 97
Total collected: 1940
Scraping page: 98
Total collected: 1960
Scraping page: 99
Total collected: 1980
Scraping page: 100
Total collected: 2000
Scraping page: 101
Total collected: 2020
Scraping page: 102
Total collected: 2040
Scraping page: 103
Total collected: 2060
Scraping page: 104
Total collected: 2080
Scraping page: 105
Total collected: 2100
Scraping page: 106
Total collected: 2120
Scraping page: 107
Total collected: 2140
Scraping page: 108
Total collected: 2160
Scraping page: 109
Total collected: 2180
Scraping page: 110
Total collected: 2200
Scraping page: 111
Total collected: 2220
Scraping page: 112
Total collected: 2240
Scraping page: 113
Total collected: 2260
Scraping page: 114
Total collected: 2280
Scraping page: 115
Total collected: 2300
Scraping page: 116
Total collected: 2320
Scraping page: 117
Total collected: 2340
Scraping page: 118
Total collected: 2360
Scraping page: 119
Total collected: 2380
Scraping page: 120
Total collected: 2400
Scraping page: 121
Total collected: 2420
Scraping page: 122
Total collected: 2440
Scraping page: 123
Total collected: 2460
Scraping page: 124
Total collected: 2480
Scraping page: 125
Total collected: 2500
Scraping page: 126
Total collected: 2520
Scraping page: 127
Total collected: 2540
Scraping page: 128
Total collected: 2560
Scraping page: 129
Total collected: 2580
Scraping page: 130
Total collected: 2600
Scraping page: 131
Total collected: 2620
Scraping page: 132
Total collected: 2640
Scraping page: 133
Total collected: 2660
Scraping page: 134
Total collected: 2680
Scraping page: 135
Total collected: 2700
Scraping page: 136
Total collected: 2720
Scraping page: 137
Total collected: 2740
Scraping page: 138
Total collected: 2760
Scraping page: 139
Total collected: 2780
Scraping page: 140
Total collected: 2800
Scraping page: 141
Total collected: 2820
Scraping page: 142
Total collected: 2840
Scraping page: 143
Total collected: 2860
Scraping page: 144
Total collected: 2880
Scraping page: 145
Total collected: 2900
Scraping page: 146
Total collected: 2920
Scraping page: 147
Total collected: 2940
Scraping page: 148
Total collected: 2960
Scraping page: 149
Total collected: 2980
Scraping page: 150
Total collected: 3000
Scraping page: 151
Total collected: 3020
Scraping page: 152
Total collected: 3040
Scraping page: 153
Total collected: 3060
Scraping page: 154
Total collected: 3080
Scraping page: 155
Total collected: 3100
Scraping page: 156
Total collected: 3120
Scraping page: 157
Total collected: 3140
Scraping page: 158
Total collected: 3160
Scraping page: 159
Total collected: 3180
Scraping page: 160
Total collected: 3200
Scraping page: 161
Total collected: 3220
Scraping page: 162
Total collected: 3240
Scraping page: 163
Total collected: 3260
Scraping page: 164
Total collected: 3280
Scraping page: 165
Total collected: 3300
Scraping page: 166
Total collected: 3320
Scraping page: 167
Total collected: 3340
Scraping page: 168
Total collected: 3360
Scraping page: 169
Total collected: 3380
Scraping page: 170
Total collected: 3400
Scraping page: 171
Total collected: 3420
Scraping page: 172
Total collected: 3440
Scraping page: 173
Total collected: 3460
Scraping page: 174
Total collected: 3480
Scraping page: 175
Total collected: 3500
Scraping page: 176
Total collected: 3520
Scraping page: 177
Total collected: 3540
Scraping page: 178
Total collected: 3560
Scraping page: 179
Total collected: 3580
Scraping page: 180
Total collected: 3600
Scraping page: 181
Total collected: 3620
Scraping page: 182
Total collected: 3640
Scraping page: 183
Total collected: 3660
Scraping page: 184
Total collected: 3680
Scraping page: 185
Total collected: 3700
Scraping page: 186
Total collected: 3720
Scraping page: 187
Total collected: 3740
Scraping page: 188
Total collected: 3760
Scraping page: 189
Total collected: 3780
Scraping page: 190
Total collected: 3800
Scraping page: 191
Total collected: 3820
Scraping page: 192
Total collected: 3840
Scraping page: 193
Total collected: 3860
Scraping page: 194
Total collected: 3880
Scraping page: 195
Total collected: 3900
Scraping page: 196
Total collected: 3920
Scraping page: 197
Total collected: 3940
Scraping page: 198
Total collected: 3960
Scraping page: 199
Total collected: 3980
Saved bewakoof_3000_products.csv

In [ ]:
import re
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

# SPEED UP CHROME
chrome_options = Options()
chrome_options.add_argument("--headless=new")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--blink-settings=imagesEnabled=false")

prefs = {
    "profile.managed_default_content_settings.images": 2,
    "profile.default_content_setting_values.notifications": 2
}
chrome_options.add_experimental_option("prefs", prefs)

driver = webdriver.Chrome(options=chrome_options)

base_url = "https://www.bewakoof.com/women-clothing?page="
rows = []

for page in range(1, 200):
    print("Scraping page:", page)

    driver.get(base_url + str(page))

    # Wait ONLY until product titles load
    t0 = time.time()
    while time.time() - t0 < 6:
        if driver.find_elements(By.XPATH, "//span[@data-testid='product-title']"):
            break
        time.sleep(0.2)

    products = driver.find_elements(By.XPATH, "//span[@data-testid='product-title']/ancestor::div[2]")

    if not products:
        print("No more products")
        break

    for product in products:
        try:
            title = product.find_element(By.XPATH, ".//span[@data-testid='product-title']").text
        except:
            title = ""

        try:
            sp = re.findall(r'₹(\d+)', product.find_element(By.XPATH, ".//span[@data-testid='product-card-selling-price']").text)[0]
        except:
            sp = ""

        try:
            mrp1 = re.findall(r'₹(\d+)', product.find_element(By.XPATH, ".//span[@data-testid='product-card-mrp']").text)[0]
        except:
            mrp1 = ""

        try:
            disc = re.findall(r'(\d+)%', product.find_element(By.XPATH, ".//span[@data-testid='product-card-discount']").text)[0]
        except:
            disc = ""

        try:
            rating1 = re.findall(r'[1-5]\.\d', product.text)[0]
        except:
            rating1 = ""

        try:
            offer1 = re.findall(r'BUY\s*\d+\s*FOR\s*\d+', product.text)[0]
        except:
            offer1 = ""

        rows.append([title, sp, mrp1, disc, rating1, offer1])
    print("Total collected:", len(rows))

driver.quit()

df = pd.DataFrame(rows, columns=["Title","Selling Price","MRP","Discount %","Rating","Offer"])
df.to_csv("bewakoof_3000_products67.csv", index=False)
print("Saved bewakoof_3000_products.csv")

Scraping page: 1
Total collected: 20
Scraping page: 2
Total collected: 40
Scraping page: 3
Total collected: 60
Scraping page: 4
Total collected: 80
Scraping page: 5
Total collected: 100
Scraping page: 6
Total collected: 120
Scraping page: 7
Total collected: 140
Scraping page: 8
Total collected: 160
Scraping page: 9
Total collected: 180
Scraping page: 10
Total collected: 200
Scraping page: 11
Total collected: 220
Scraping page: 12
Total collected: 240
Scraping page: 13
Total collected: 260
Scraping page: 14
Total collected: 280
Scraping page: 15
Total collected: 300
Scraping page: 16
Total collected: 320
Scraping page: 17
Total collected: 340
Scraping page: 18
Total collected: 360
Scraping page: 19
Total collected: 380
Scraping page: 20
Total collected: 400
Scraping page: 21
Total collected: 420
Scraping page: 22
Total collected: 440
Scraping page: 23
Total collected: 460
Scraping page: 24
Total collected: 480
Scraping page: 25
Total collected: 500
Scraping page: 26
Total collected: 520
Scraping page: 27
Total collected: 540
Scraping page: 28
Total collected: 560
Scraping page: 29
Total collected: 580
Scraping page: 30
Total collected: 600
Scraping page: 31
Total collected: 620
Scraping page: 32
Total collected: 640
Scraping page: 33
Total collected: 660
Scraping page: 34
Total collected: 680
Scraping page: 35
Total collected: 700
Scraping page: 36
Total collected: 720
Scraping page: 37
Total collected: 740
Scraping page: 38
Total collected: 760
Scraping page: 39
Total collected: 780
Scraping page: 40
Total collected: 800
Scraping page: 41
Total collected: 820
Scraping page: 42
Total collected: 840
Scraping page: 43
Total collected: 860
Scraping page: 44
Total collected: 880
Scraping page: 45
Total collected: 900
Scraping page: 46
Total collected: 920
Scraping page: 47
Total collected: 940
Scraping page: 48
Total collected: 960
Scraping page: 49
Total collected: 980
Scraping page: 50
Total collected: 1000
Scraping page: 51
Total collected: 1020
Scraping page: 52
Total collected: 1040
Scraping page: 53
Total collected: 1060
Scraping page: 54
Total collected: 1080
Scraping page: 55
Total collected: 1100
Scraping page: 56
Total collected: 1120
Scraping page: 57
Total collected: 1140
Scraping page: 58
Total collected: 1160
Scraping page: 59
Total collected: 1180
Scraping page: 60
Total collected: 1200
Scraping page: 61
Total collected: 1220
Scraping page: 62
Total collected: 1240
Scraping page: 63
Total collected: 1260
Scraping page: 64
Total collected: 1280
Scraping page: 65
Total collected: 1300
Scraping page: 66
Total collected: 1320
Scraping page: 67
Total collected: 1340
Scraping page: 68
Total collected: 1360
Scraping page: 69
Total collected: 1380
Scraping page: 70
Total collected: 1400
Scraping page: 71
Total collected: 1420
Scraping page: 72
Total collected: 1440
Scraping page: 73
Total collected: 1460
Scraping page: 74
Total collected: 1480
Scraping page: 75
Total collected: 1500
Scraping page: 76
Total collected: 1520
Scraping page: 77
Total collected: 1540
Scraping page: 78
Total collected: 1560
Scraping page: 79
Total collected: 1580
Scraping page: 80
Total collected: 1600
Scraping page: 81
Total collected: 1620
Scraping page: 82
Total collected: 1640
Scraping page: 83
Total collected: 1660
Scraping page: 84
Total collected: 1680
Scraping page: 85
Total collected: 1700
Scraping page: 86
Total collected: 1720
Scraping page: 87
Total collected: 1740
Scraping page: 88
Total collected: 1760
Scraping page: 89
Total collected: 1780
Scraping page: 90
Total collected: 1800
Scraping page: 91
Total collected: 1820
Scraping page: 92
Total collected: 1840
Scraping page: 93
Total collected: 1860
Scraping page: 94
Total collected: 1880
Scraping page: 95
Total collected: 1900
Scraping page: 96
Total collected: 1920
Scraping page: 97
Total collected: 1940
Scraping page: 98
Total collected: 1960
Scraping page: 99
Total collected: 1980
Scraping page: 100
Total collected: 2000
Scraping page: 101
Total collected: 2020
Scraping page: 102
Total collected: 2040
Scraping page: 103
Total collected: 2060
Scraping page: 104
Total collected: 2080
Scraping page: 105
Total collected: 2100
Scraping page: 106
Total collected: 2120
Scraping page: 107
Total collected: 2140
Scraping page: 108
Total collected: 2160
Scraping page: 109
Total collected: 2180
Scraping page: 110
Total collected: 2200
Scraping page: 111
Total collected: 2220
Scraping page: 112
Total collected: 2240
Scraping page: 113
Total collected: 2260
Scraping page: 114
Total collected: 2280
Scraping page: 115
Total collected: 2300
Scraping page: 116
Total collected: 2320
Scraping page: 117
Total collected: 2340
Scraping page: 118
Total collected: 2360
Scraping page: 119
Total collected: 2380
Scraping page: 120
Total collected: 2400
Scraping page: 121
Total collected: 2420
Scraping page: 122
Total collected: 2440
Scraping page: 123
Total collected: 2460
Scraping page: 124
Total collected: 2480
Scraping page: 125
Total collected: 2500
Scraping page: 126
Total collected: 2520
Scraping page: 127
Total collected: 2540
Scraping page: 128
Total collected: 2560
Scraping page: 129
Total collected: 2580
Scraping page: 130
Total collected: 2600
Scraping page: 131
Total collected: 2620
Scraping page: 132
Total collected: 2640
Scraping page: 133
Total collected: 2660
Scraping page: 134
Total collected: 2680
Scraping page: 135
Total collected: 2700
Scraping page: 136
Total collected: 2720
Scraping page: 137
Total collected: 2740
Scraping page: 138
Total collected: 2760
Scraping page: 139
Total collected: 2780
Scraping page: 140
Total collected: 2800
Scraping page: 141
Total collected: 2820
Scraping page: 142
Total collected: 2840
Scraping page: 143
Total collected: 2860
Scraping page: 144
Total collected: 2880
Scraping page: 145
Total collected: 2900
Scraping page: 146
Total collected: 2920
Scraping page: 147
Total collected: 2940
Scraping page: 148
Total collected: 2960
Scraping page: 149
Total collected: 2980
Scraping page: 150
Total collected: 3000
Scraping page: 151
Total collected: 3020
Scraping page: 152
Total collected: 3040
Scraping page: 153
Total collected: 3060
Scraping page: 154
Total collected: 3080
Scraping page: 155
Total collected: 3100
Scraping page: 156
Total collected: 3120
Scraping page: 157
Total collected: 3140
Scraping page: 158
Total collected: 3160
Scraping page: 159
Total collected: 3180
Scraping page: 160
Total collected: 3200
Scraping page: 161
Total collected: 3220
Scraping page: 162
Total collected: 3240
Scraping page: 163
Total collected: 3260
Scraping page: 164
Total collected: 3280
Scraping page: 165
Total collected: 3300
Scraping page: 166
Total collected: 3320
Scraping page: 167
Total collected: 3340
Scraping page: 168
Total collected: 3360
Scraping page: 169
Total collected: 3380
Scraping page: 170
Total collected: 3400
Scraping page: 171
Total collected: 3420
Scraping page: 172
Total collected: 3440
Scraping page: 173
Total collected: 3460
Scraping page: 174
Total collected: 3480
Scraping page: 175
Total collected: 3500
Scraping page: 176
Total collected: 3520
Scraping page: 177
Total collected: 3540
Scraping page: 178
Total collected: 3560
Scraping page: 179
Total collected: 3580
Scraping page: 180
Total collected: 3600
Scraping page: 181
Total collected: 3620
Scraping page: 182
Total collected: 3640
Scraping page: 183
Total collected: 3660
Scraping page: 184
Total collected: 3680
Scraping page: 185
Total collected: 3700
Scraping page: 186
Total collected: 3720
Scraping page: 187
Total collected: 3740
Scraping page: 188
Total collected: 3760
Scraping page: 189
Total collected: 3780
Scraping page: 190
Total collected: 3800
Scraping page: 191
Total collected: 3820
Scraping page: 192
Total collected: 3840
Scraping page: 193
Total collected: 3860
Scraping page: 194
Total collected: 3880
Scraping page: 195
Total collected: 3900
Scraping page: 196
Total collected: 3920
Scraping page: 197
Total collected: 3940
Scraping page: 198
Total collected: 3960
Scraping page: 199
Total collected: 3980
Saved bewakoof_3000_products.csv

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [ ]:
data=pd.read_csv('D:\\Cars24_Analysis\\Notebooks\\bewakoof_3000_products.csv')
data.head()

,Title,Selling Price,MRP,Discount %,Rating,Offer
0,Men's Grey Pyjamas,579,1,55,NaN,BUY 2 FOR 1099
1,Men's Blue Dementors Graphic Printed T-shirt,499,1,56,NaN,BUY 3 FOR 1099
2,Men's Black Freedom Sounds Graphic Printed Ove...,799,2,63,NaN,NaN
3,Men's Maroon Dead Pool Jersey Graphic Printed ...,659,1,49,NaN,BUY 2 FOR 1099
4,Men's Green Wakanda Forever Graphic Printed Ov...,699,1,51,NaN,BUY 2 FOR 1099

In [ ]:
data.shape

(3980, 6)

In [ ]:
data1=pd.read_csv('D:\\Cars24_Analysis\\Notebooks\\bewakoof_3000_products67.csv')
data1.head()

,Title,Selling Price,MRP,Discount %,Rating,Offer
0,Women's Orange Boyfriend T-shirt,399,699,42,NaN,BUY 3 FOR 1099
1,Women's Black Zipper Hoodies,1,1,47,NaN,NaN
2,Women's Brick Red Boyfriend T-shirt,399,1,69,NaN,BUY 3 FOR 1099
3,Women's Pink & White Camo Printed Oversized T-...,599,1,47,NaN,BUY 2 FOR 1099
4,Women's Black Patch Minion Graphic Printed Ove...,599,1,60,NaN,BUY 2 FOR 1099

In [ ]:
data1.shape

(3980, 6)

In [ ]:
df = pd.concat([data, data1], ignore_index=True)
df.head()

,Title,Selling Price,MRP,Discount %,Rating,Offer
0,Men's Grey Pyjamas,579,1,55,NaN,BUY 2 FOR 1099
1,Men's Blue Dementors Graphic Printed T-shirt,499,1,56,NaN,BUY 3 FOR 1099
2,Men's Black Freedom Sounds Graphic Printed Ove...,799,2,63,NaN,NaN
3,Men's Maroon Dead Pool Jersey Graphic Printed ...,659,1,49,NaN,BUY 2 FOR 1099
4,Men's Green Wakanda Forever Graphic Printed Ov...,699,1,51,NaN,BUY 2 FOR 1099

In [ ]:
df.shape

(7960, 6)

In [ ]:
df.to_csv('D:\\Cars24_Analysis\\Notebooks\\bewakoof_full_data.csv', index=False)

In [ ]:
df1=pd.read_csv('D:\\Cars24_Analysis\\Notebooks\\bewakoof_full_data.csv')
df1.head()

,Title,Selling Price,MRP,Discount %,Rating,Offer
0,Men's Grey Pyjamas,579,1,55,NaN,BUY 2 FOR 1099
1,Men's Blue Dementors Graphic Printed T-shirt,499,1,56,NaN,BUY 3 FOR 1099
2,Men's Black Freedom Sounds Graphic Printed Ove...,799,2,63,NaN,NaN
3,Men's Maroon Dead Pool Jersey Graphic Printed ...,659,1,49,NaN,BUY 2 FOR 1099
4,Men's Green Wakanda Forever Graphic Printed Ov...,699,1,51,NaN,BUY 2 FOR 1099

In [ ]:
df1.shape

(7960, 6)

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

# -------------------- SETUP --------------------
options = webdriver.ChromeOptions()
options.add_argument("--start-maximized")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

url = "https://www.bewakoof.com/winter-wear-for-men"
driver.get(url)

wait = WebDriverWait(driver, 10)

# wait until first product loads
wait.until(
    EC.presence_of_element_located(
        (By.CSS_SELECTOR, '[data-testid="product-card-info-wrapper"]')
    )
)

# -------------------- AUTO SCROLL --------------------
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(2.5)

    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height

# -------------------- DATA EXTRACTION --------------------
product_cards = driver.find_elements(
    By.XPATH,
    "//div[@data-testid='product-card-info-wrapper']/ancestor::div[contains(@class,'ProductCard')]"
)

print("Total products found:", len(product_cards))

data = []

for card in product_cards:

    def safe_text(xpath):
        try:
            return card.find_element(By.XPATH, xpath).text
        except:
            return None

    rating = safe_text(".//span[contains(text(),'⭐')]")
    if rating:
        rating = rating.replace("⭐", "").strip()

    data.append({
        "title": safe_text(".//span[@data-testid='product-title']"),
        "price": safe_text(".//span[@data-testid='product-card-selling-price']"),
        "mrp": safe_text(".//span[@data-testid='product-card-mrp']"),
        "discount": safe_text(".//span[@data-testid='product-card-discount']"),
        "rating": rating
    })

driver.quit()

# -------------------- SAVE TO CSV --------------------
df = pd.DataFrame(data).drop_duplicates()
df.to_csv("bewakoof_winter_wear_men.csv", index=False, encoding="utf-8-sig")

print(f"Saved {len(df)} products to bewakoof_winter_wear_men.csv")

Total products found: 0
Saved 0 products to bewakoof_winter_wear_men.csv

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time

# ---------------- SETUP ----------------
options = webdriver.ChromeOptions()
options.add_argument("--start-maximized")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

url = "https://www.bewakoof.com/winter-wear-for-men"
driver.get(url)

wait = WebDriverWait(driver, 15)

wait.until(
    EC.presence_of_element_located(
        (By.CSS_SELECTOR, '[data-testid="product-card-info-wrapper"]')
    )
)

# ---------------- AUTO SCROLL ----------------
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(3)

    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height

# ---------------- DATA EXTRACTION ----------------
products = driver.find_elements(
    By.CSS_SELECTOR,
    '[data-testid="product-card-info-wrapper"]'
)

print("Total products found:", len(products))

data = []

for product in products:

    def safe_text(by, value):
        try:
            return product.find_element(by, value).text
        except:
            return None

    title = safe_text(By.CSS_SELECTOR, '[data-testid="product-title"]')
    price = safe_text(By.CSS_SELECTOR, '[data-testid="product-card-selling-price"]')
    mrp = safe_text(By.CSS_SELECTOR, '[data-testid="product-card-mrp"]')
    discount = safe_text(By.CSS_SELECTOR, '[data-testid="product-card-discount"]')

    # ⭐ rating is OUTSIDE info-wrapper → use JS to search parent
    try:
        rating = product.find_element(
            By.XPATH,
            "../..//span[contains(text(),'⭐')]"
        ).text
        rating = rating.replace("⭐", "").strip()
    except:
        rating = None

    data.append({
        "title": title,
        "price": price,
        "mrp": mrp,
        "discount": discount,
        "rating": rating
    })

driver.quit()

# ---------------- SAVE CSV ----------------
df = pd.DataFrame(data).drop_duplicates()
df.to_csv("bewakoof_winter_wear_menjatoth.csv", index=False, encoding="utf-8-sig")

print(f"Saved {len(df)} products to bewakoof_winter_wear_men.csv")

WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=144.0.7559.60)
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x4f7d13
	0x4f7d54
	0x31b290
	0x31879e
	0x30b814
	0x30d26c
	0x30bcb7
	0x30b5e5
	0x30b2e5
	0x3093f8
	0x309b0a
	0x31ed1e
	0x3a5c54
	0x387fbc
	0x3a5111
	0x387d56
	0x3594d9
	0x35a294
	0x76bb64
	0x767215
	0x783fad
	0x511ef8
	0x519b0d
	0x500738
	0x500902
	0x4ea1da
	0x74c27ba9
	0x76fcc3ab
	0x76fcc32f

In [ ]:
print(response.status_code)
print(response.headers.get("content-type"))
print(response.text[:500])

404
text/html; charset=utf-8

      <!doctype html>
        <head>

        <meta name="google-site-verification" content="4d8KRpUCzf-ghquF_HLNphibw_xRvUS3kAvzpnF2KlA" />
        <meta name="google-site-verification" content="-TTsyPFCOB4bQlMHawiO4oZGcGX9pxqenB_NZNhhhgA" />
        <meta name="google-site-verification" content="wQa0CQvt7fd2VIoa9qhkevhvwuBvhRwiaB3hVizI9OY" />
        <meta name="google-site-verification" content="o7KS3-fVt15m4Cc1HeYh5HIpv532A4FvvYQzIf-LnsQ" />

        <link rel="preconnect" href="htt

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
driver.get("https://www.bewakoof.com/winter-wear-for-men")
time.sleep(5)

product_links = set()
last_height = 0

while True:
    cards = driver.find_elements(By.XPATH, "//a[contains(@href,'/men')]")
    for c in cards:
        link = c.get_attribute("href")
        if link:
            product_links.add(link)

    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(2)

    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height

driver.quit()

print("Total product links:", len(product_links))

Total product links: 45

In [ ]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

data = []

for url in list(product_links):
    driver.get(url)
    time.sleep(2)

    def safe(xpath):
        try:
            return driver.find_element(By.XPATH, xpath).text
        except:
            return None

    data.append({
        "url": url,
        "title": safe("//h1"),
        "price": safe("//span[contains(text(),'₹')]"),
        "rating": safe("//span[contains(text(),'⭐')]")
    })

driver.quit()

pd.DataFrame(data).to_csv("bewakoof_full_data.csv", index=False)

In [ ]:
df=pd.read_csv('D:\\Cars24_Analysis\\Notebooks\\bewakoof_full_data.csv')
df.head()

,url,title,price,rating
0,https://www.bewakoof.com/mens-combo-t-shirt,T-shirt Combo for Men,FREE SHIPPING on all orders above ₹399,NaN
1,https://www.bewakoof.com/p/mens-jet-black-prin...,NaN,"₹2,499",NaN
2,https://www.bewakoof.com/p/mens-fig-brown-over...,NaN,"₹3,199",NaN
3,https://www.bewakoof.com/mens-innerwear,Men's Innerwear,FREE SHIPPING on all orders above ₹399,NaN
4,https://www.bewakoof.com/p/mens-red-white-colo...,NaN,"₹3,199",NaN